Document: flipper
Title: Debian flipper Manual
Author: <insert document author here>
Abstract: This manual describes what flipper is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/flipper/flipper.sgml.gz

Format: postscript
Files: /usr/share/doc/flipper/flipper.ps.gz

Format: text
Files: /usr/share/doc/flipper/flipper.text.gz

Format: HTML
Index: /usr/share/doc/flipper/html/index.html
Files: /usr/share/doc/flipper/html/*.html
